CREATE TABLE app_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    title VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    start_date_time TIMESTAMP NOT NULL ,
    end_date_time TIMESTAMP NOT NULL ,
    price DECIMAL(19, 2) NOT NULL ,
    capacity INT NOT NULL ,
    status VARCHAR(20) NOT NULL ,
    category_id BIGINT NOT NULL ,
    venue_id BIGINT NOT NULL ,

    CONSTRAINT fk_event_category
            FOREIGN KEY (category_id)
            REFERENCES  app_category(id),

    CONSTRAINT fk_event_venue
            FOREIGN KEY (venue_id)
            REFERENCES  app_venue(id)
);