CREATE TABLE app_booking (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    event_id BIGINT NOT NULL ,
    customer_id BIGINT NOT NULL ,
    quantity INT NOT NULL ,
    total_price DECIMAL(19, 2) NOT NULL ,
    status VARCHAR(20) NOT NULL ,
    created_at TIMESTAMP NOT NULL ,
    updated_at TIMESTAMP NOT NULL ,

    CONSTRAINT fk_booking_event
            FOREIGN KEY (event_id)
            REFERENCES app_event(id),

    CONSTRAINT fk_booking_customer
            FOREIGN KEY (customer_id)
            REFERENCES app_customer(id)
);