CREATE TABLE app_review (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    rating INT NOT NULL ,
    comment VARCHAR(500) ,
    created_at TIMESTAMP NOT NULL ,
    updated_at TIMESTAMP NOT NULL ,
    customer_id BIGINT NOT NULL ,
    event_id BIGINT NOT NULL ,

    CONSTRAINT fk_review_customer
            FOREIGN KEY (customer_id)
            REFERENCES app_customer(id),

    CONSTRAINT fk_review_event
            FOREIGN KEY (event_id)
            REFERENCES app_event(id),

    CONSTRAINT uk_review_customer_event
            UNIQUE (customer_id, event_id)
)